### PR TITLE
Improved documentation about Brainsight .txt reading / writing

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@oulap friendly ping... did you have a chance to look this over?

**Comment by seanm** [comment]
@oulap Why does the text in master recommend "Choose `NIfTI:Aligned` coordinate system"?  Is it because charm (or whatever) always creates NIfTI files with the `NIFTI_XFORM_ALIGNED_ANAT` intent code?

**Comment by oulap** [comment]
Hi @seanm,

I don't know too much about the neuronavigation import/export, but we would like to make the instructions for simnibs users as simple and straight-forward as possible. charm will always force the q- and s-forms to be the same (although you can now choose if you force the q or the s). I'm not sure how this relates to the options in brainsight, but if NifTI:Aligned is not the correct one then we're of course more than happy to update the documentation. In any case, it would be great if we could have the brainsight import documented so that simnibs users do not have to juggle between too many options.

**Comment by seanm** [comment]
@oulap thanks for your reply.

>we would like to make the instructions for simnibs users as simple and straight-forward as possible

I'm all for simple, clear, and correct instructions!

>charm will always force the q- and s-forms to be the same (although you can now choose if you force the q or the s).

So it always sets `qform_code` and `sform_code` to be the same, but does it always use `NIFTI_XFORM_ALIGNED_ANAT` (aka `2`)?  Or does it sometimes use other values?

>I'm not sure how this relates to the options in brainsight...

I've tried to describe that in this PR, but to give two concrete examples:

1. If the file has qform_code=1 and sform_code=2, then:

Brainsight 2.5.2 will give two coordinate system options: `NIfTI:Scanner` and `NIfTI:Aligned`

Brainsight 2.5.3 (coming soon) will give two coordinate system options but with an improved name giving the detail of where they came from: `NIfTI:Q:Scanner` and `NIfTI:S:Aligned`.

2. If the file has qform_code=2 and sform_code=2, then:

Brainsight 2.5.2 will give one coordinate system option: `NIfTI:Aligned` (and it will be from the qform)

Brainsight 2.5.3 (coming soon) will give two coordinate system options: `NIfTI:Q:Aligned` and `NIfTI:S:Aligned`.

**Comment by seanm** [comment]
>So it always sets qform_code and sform_code to be the same, but does it always use NIFTI_XFORM_ALIGNED_ANAT (aka 2)? Or does it sometimes use other values?

@oulap would you know the answer to this? Thanks.

**Comment by oulap** [comment]
Hi @seanm 

Sorry for taking so long! We had a SimNIBS meeting today and discussed the how to handle the q- and s-form business. Basically what we will do is the following: SimNIBS will by default use the qform matrix and copy the qform matrix and qform_code to the sform to avoid inconsistencies. You can also use the sform if you want to, but this needs to be separately forced, and SimNIBS will in this case copy the sform matrix and code over to the qform (stripping shears in the process). In this case the qform is also copied back to the sform matrix to make sure they are the same in case there were shears.

For import and export to and from brainsight there should not be a problem as long as the Q-option is used and the qform exists and is set correctly. The code can be either scanner or aligned.

Does that make sense?

**Comment by seanm** [comment]
> Does that make sense?

Mmmm, sort of.  Are you talking about what is done today?, or some change you will make in the future?

I'm mostly concerned with today's SimNIBS.  Brainsight 2.5.3 is being released in a about a week.

**Comment by oulap** [comment]
What I described is how we will do in the future. Today's SimNIBS does not look at the codes just the matrices. In most cases the qform is forced and thus the correct choice would be whatever the qform_code is. However, if the user forces the sform the matrices are updated to be consistent but the codes are not. In any case, as long as the qform is set properly and the user chooses that option in brainsight there should not be problems with importing to simnibs.

**Comment by seanm** [comment]
> Today's SimNIBS does not look at the codes just the matrices. In most cases the qform is forced and thus the correct choice would be whatever the qform_code is. However, if the user forces the sform the matrices are updated to be consistent but the codes are not. In any case, as long as the qform is set properly and the user chooses that option in brainsight there should not be problems with importing to simnibs.

So there are two ways Brainsight and SimNIBS interact:

1. the user can export from Brainsight a .txt file. Here we provide a UI for the user to choose which coordinate system to export as. Your code in nnav.py can parse this format.
2. the user can press a button to automatically invoke SimNIBS. Here we run a python script that creates `SESSION`, `TMSLIST`, and `POSITION`.  In this case we don't provide any UI to choose coordinate system, we instead always use the 'correct' coordinate system. And I'm trying to make sure we are doing this properly.  [This document](https://simnibs.github.io/simnibs/build/html/documentation/coordinates.html#coords-doc) doesn't say anything about s vs q for example.  So if I'm understanding what you said above correctly, here we should always use qform, never sform. Correct?

**Comment by oulap** [comment]
Correct, it's somewhat implicitly stated here:

https://simnibs.github.io/simnibs/build/html/documentation/neuronavigation/neuronavigation.html

i.e., that when you use the scan processed with charm using the --forceqform flag everything should be consistent.

**Comment by seanm** [comment]
OK great. I'll make Brainsight 2.5.3 always use qform for case 2 then.

For case 1, looking at [this code](https://github.com/simnibs/simnibs/blob/e15afab5712838fe728e62f29505172f8d096fd8/simnibs/utils/nnav.py#L460-L462) of yours:

```
            if coord_sys.lower() != 'nifti:aligned':
                raise ValueError(f"Coordinate system '{coord_sys}' is not supported. "
                                 f"Export targes/samples as NIfTI:Aligned.")
```

It seems you are looking at our .txt file's `# Coordinate system:` line, but only accepting exactly that value, not others.  I described above how that line is defined by Brainsight 2.5.2 and earlier, how it's changing in 2.5.3.  This code will need updating for Brainsight 2.5.3.  We can create a PR...

**Comment by oulap** [comment]
Thanks, I'm including @0nu here. He's the original author of the import/export from brainsight module. 

@0nu : was there a specific reason to only accept "align" and not "scanner"?

**Comment by seanm** [comment]
I've made a small change to this PR based on today's discussions (prefer q over s).  IMHO it is ready for review & merge.

>We had a SimNIBS meeting today and discussed the how to handle the q- and s-form business.

Regarding future changes, do as you think best of course, but I'll just note that, for whatever reason, NiBabel and BabelBrain use this algorithm: https://nipy.org/nibabel/nifti_images.html#choosing-image-affine

**Comment by seanm** [comment]
My colleague has made a SimNIBS code change here for our change to our .txt format: https://github.com/simnibs/simnibs/pull/289

**Comment by seanm** [comment]
Thanks!

**Comment by oulap** [comment]
Thanks for the PR!

**Pull request merged**
